name: GitHub Actions - CI branch dev

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  testsuite_linux_arm:
    name: "Test Suite (Linux arm64)"
    runs-on: ubuntu-26.04-arm
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true

  testsuite_linux:
    name: "Test Suite (Linux x64)"
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true

  testsuite_win_arm:
    name: "Test Suite (Windows arm64)"
    runs-on: windows-11-arm
    defaults:
      run:
        shell: bash # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defaultsrunshell
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, pdo_sqlite
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true

  testsuite_win:
    name: "Test Suite (Windows x64)"
    runs-on: windows-2025
    defaults:
      run:
        shell: bash # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defaultsrunshell
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, pdo_sqlite
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true

  testsuite_macos:
    name: "Test Suite (macOS arm64)"
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true

  testsuite_macos_intel:
    name: "Test Suite (macOS Intel)"
    runs-on: macos-26-intel
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.5'

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer i -n --prefer-dist --no-progress

      - name: Run tests with PHPs >= 8.1
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Run tests with PHPs < 8.1
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --configuration phpunit-legacy.dist.xml --verbose --coverage-clover=tests/coverage.xml --log-junit=tests/junit.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          files: ./tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./tests/junit.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true
